version: '2.1'
services:
  api:
    container_name: nest_server
    restart: always
    build: .
    ports:
      - '${APP_PORT}:3000'
    depends_on:
      database:
        condition: service_healthy
    command: /bin/sh -c "npm run typeorm migration:run && node ./dist/main.js"
    links:
      - database
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRE=${JWT_EXPIRE}
      - APP_PORT=${APP_PORT}
      - DB_TYPE=${DB_TYPE}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

  database:
    container_name: ${DB_HOST}
    image: postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 10s
      retries: 120
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
volumes:
  data: {}
